### ISSUE TITLE
Training my own model

### ISSUE THREAD

**Issue by ghost** [qurator-spk/sbb_textline_detection#14]
Thank you for your hard work,

It would be great if the training script and guide are included, so that I can train my own models.
Waiting for your reply

**Comment by vahidrezanezhad** [comment]
Dear @deepseek, you can use this repo to train your own model. please do not hesitate to contact me if you have any difficulty.

https://github.com/qurator-spk/pixelwise_segmentation

**Comment by ghost** [comment]
@vahidrezanezhad 

Sample Ground-Truth:
- Upload a sample ground-truth to train a **text-line** detection model on sbb_pixelwise_segmentation along with it's `config_params.json`.
- Upload a sample ground-truth to train a **multi-class** detection model on sbb_pixelwise_segmentation along with it's `config_params.json`.

Questions:
- Did you train all the models (page, page_new, strukturerkennung, textline) using `sbb_pixelwise_segmentation`? all at once using multiple number of classes? 
- If I want to train using `resnet50_unet_light` I should change [`train.py#L146`](https://github.com/qurator-spk/sbb_pixelwise_segmentation/blob/master/train.py#L146) from `resnet50_unet` to `resnet50_unet_light`?
- For `sbb_textline_detector`, it can detect text-lines only if I trained all (page, region, textline) models?

**Comment by vahidrezanezhad** [comment]
Dear @deepseek 

Sample GT,

You can find sample data and corresponding config_params.json for each use case here:
https://file.spk-berlin.de:8443/sample_data_for_pixelwise_training/

Questions:
- Yes I use sbb_pixelwise_segmentation for all use cases and even for binarization.

- Thats true. If you want to have a light training model just use light version. If you want to see the model structure you can uncomment model.summary() in train.py.

- No, the name is confusing but this tool has a page-xml output which consist of print space(page), Regions(text, separators, images and background ) and textlines.

**Comment by ghost** [comment]
Thanks man, hoping that you continue being amazing!
