### ISSUE TITLE
ocrd-sbb-text-line-detector writes PAGE output to stdout

### ISSUE THREAD

**Issue by mikegerber** [qurator-spk/sbb_textline_detection#16]
As reported by @wrznr in Gitter

**Comment by mikegerber** [comment]
The problem is here: https://github.com/OCR-D/core/blob/master/ocrd_models/ocrd_models/ocrd_page_generateds.py#L9645. I'm going to set `silence`.

@kba Not sure if it qualifies as a bug that `parse()` is not silent by default.

**Comment by mikegerber** [comment]
Fixed in https://github.com/qurator-spk/sbb_textline_detector/commit/11c0e9cee54d2a5c9a4683a897608ba11a29bf73

**Comment by kba** [comment]
We should document that in the code. Since we're just importing the method from generateDS, I'm not sure how though.
