### ISSUE TITLE
Warn about or refuse overwriting existing elements

### ISSUE THREAD

**Issue by wrznr** [qurator-spk/sbb_textline_detection#17]
The OCR-D processor silently overwrites existing annotations in the PAGE XML. It should be made either made clear via documentation and/or logging that this happens or maybe the processor should refuse to do so and require explicit confirmation via a parameter.

**Comment by mikegerber** [comment]
I'll do two things:

* [x] Update the README that this also does printspace and region detection.
* [x] I'll let the OCR-D processor give a warning if those segments already exist

**Comment by mikegerber** [comment]
Fixed in https://github.com/qurator-spk/sbb_textline_detector/commit/27b2d056b0e2e430fcc0df772f4610ee032fde8e and https://github.com/qurator-spk/sbb_textline_detector/commit/f90b3cfa8601c20c8401095209c00dfbb43c5a78.
