### ISSUE TITLE
Reportedly, there may be an issue with deskewing

### ISSUE THREAD

**Issue by wrznr** [qurator-spk/sbb_textline_detection#18]
@mikegerber asked me to upload the following example as a reference for a possible deskewing issue:

**Line level**
![image](https://user-images.githubusercontent.com/26707219/70620497-c1d4dd80-1c17-11ea-91f5-3dd15a993f21.png)

**Region level**
![image](https://user-images.githubusercontent.com/26707219/70620544-db762500-1c17-11ea-80f5-48c3c25ec433.png)

**Original**
https://digital.slub-dresden.de/data/kitodo/Brsfded_39946221X-19020630/Brsfded_39946221X-19020630_tif/jpegs/00000001.tif.original.jpg

**Comment by mikegerber** [comment]
@vahidrezanezhad The problem I saw here was in the header of the page:

![Screenshot_2019-12-11_13-41-17](https://user-images.githubusercontent.com/34309482/70622315-f34fa800-1c1b-11ea-9e9c-7e0bd4a77199.png)

**Comment by vahidrezanezhad** [comment]
For deskewing I am using textline-segmentation result, so if the segmentation result is not perfect deskewing can face difficulty . This probably will be solved with new texline model :)

**Comment by mikegerber** [comment]
@vahidrezanezhad So I'm closing this, just told @wrznr to open an issue because I thought the example could be interesting 🙂
