### ISSUE TITLE
2D vs 3D Training

### ISSUE THREAD

**Issue by ghost** [qurator-spk/sbb_textline_detection#21]
@vahidrezanezhad 
When preparing the training data ground-truth, at what cases should I use 2D, and what cases should I use 3D?

Does using 3D means that I can train a single model containing page+region+lines?

**Comment by vahidrezanezhad** [comment]
@deepseek  To prepare GT to train with our script you need 2d as option. 3d option has nothing to do with page, region or textlines, with 3d It means that each class is identified with a unique RGB. (in 2d for each class  I give a unique number for a pixel).

**Comment by ghost** [comment]
Thanks
