### ISSUE TITLE
models download link is down

### ISSUE THREAD

**Issue by Mohamed209** [qurator-spk/sbb_textline_detection#23]
it seems that that model download link is corrupted
`
This site can’t be reachedThe webpage at https://file.spk-berlin.de:8443/textline_detection/ might be temporarily down or it may have moved permanently to a new web address.
ERR_TUNNEL_CONNECTION_FAILED
`

**Comment by cneud** [comment]
@Mohamed209 Apologies, but our fileserver where this (and other) models were hosted has been permanently taken down. We're already investigating alternative hosting options, hopefully we can find a stopgap or even longer-term solution next week!

**Comment by cneud** [comment]
@Mohamed209 Please find the updated download link for the models here: https://qurator-data.de/sbb_textline_detector/
