### ISSUE TITLE
replace PrintSpace with Border

### ISSUE THREAD

**Issue by bertsky** [qurator-spk/sbb_textline_detection#29]
I'm not sure if this is intentional, but currently the textline detector uses the `PrintSpace` element for the outer hull of all detected regions. Shouldn't that be `Border` instead?

See also:
- https://github.com/OCR-D/core/issues/488
- https://ocr-d.de/en/gt-guidelines/trans/lySatzspiegel.html

Here are the two affected places:

https://github.com/qurator-spk/sbb_textline_detection/blob/d36b01591d2328fc03f2956ff98b66e50a5f81f5/qurator/sbb_textline_detector/main.py#L1941

https://github.com/qurator-spk/sbb_textline_detection/blob/d36b01591d2328fc03f2956ff98b66e50a5f81f5/qurator/sbb_textline_detector/ocrd_cli.py#L83-L85

**Comment by cneud** [comment]
Thanks, I would prefer to be in line with current @OCR-D conventions here, but let me check this with @vahidrezanezhad @mikegerber (see also [PrintSpaceType](https://ocr-d.de/en/gt-guidelines/pagexml/pagecontent_xsd_Complex_Type_pc_PrintSpaceType.html) vs [BorderType](https://ocr-d.de/en/gt-guidelines/pagexml/pagecontent_xsd_Complex_Type_pc_BorderType.html))

**Comment by bertsky** [comment]
Note, also affects the tool's problem statement in the README:
> This tool performs printspace, region and textline detection

How about:
> This tool performs page frame, text region and text line detection (i.e. page cropping, page segmentation and line segmentation)

BTW, this also makes me wonder how well your method can cope with _textual noise_ (like facing pages). Even the (rule-based) [DFKI tool](https://github.com/OCR-D/ocrd_anybaseocr/blob/master/ocrd_anybaseocr/cli/ocrd_anybaseocr_cropping.py) has problems with pages [like this](https://user-images.githubusercontent.com/38561704/81486239-aff17800-9253-11ea-824b-5050125b3111.png) where the gutter is non-vertical...

**Comment by cneud** [comment]
Nice example ;) I don't think our current model is very optimized for that yet, but @vahidrezanezhad is already experimenting with new models for e.g. curved lines.

I can however remember [2007](http://www.imlab.jp/cbdar2007/proceedings/papers/P2.pdf) and [2010](https://dl.acm.org/doi/pdf/10.1145/1815330.1815382) IMPACT NCSR implementations being able to deal with such pages.

**Comment by bertsky** [comment]
>  I don't think our current model is very optimized for that yet

You were right. It does detect that the right side does not belong to the page – sort of – but then uses a bbox which forces parts of the noise into the page frame again:
![OCR-D-CROP-SBB_0001](https://user-images.githubusercontent.com/38561704/83080976-e155aa80-a07f-11ea-95d6-80649feb6e12.png)

Maybe this is just a matter of using polygons instead of bboxes?
