### ISSUE TITLE
make Tensorflow less gabby

### ISSUE THREAD

**Issue by bertsky** [qurator-spk/sbb_textline_detection#30]
Running the detector prints loads of unnecessary and (to non-developers) confusing TF messages.

Please consider doing the following to silence them to actual errors:

- before importing TF (or Keras, or whatever imports TF): `os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'`
- after importing TF: `tf.get_logger().setLevel('ERROR')`

Getting the TF logger to adhere to OCR-D conventions is another story, but there I cannot offer a solution for now.

**Comment by kba** [comment]
Would it help if we set the TF logging level in `initLogging` in core, like we do for PIL and shapely?

**Comment by bertsky** [comment]
> Would it help if we set the TF logging level in `initLogging` in core, like we do for PIL and shapely?

I don't know, but it sounds like a great idea. Let's try it out!

**Comment by vahidrezanezhad** [comment]
@bertsky I will take it into account. Thanks

**Comment by mikegerber** [comment]
@vahidrezanezhad Can this be closed?

0f09f4a says it's resolved.

**Comment by bertsky** [comment]
> Getting the TF logger to adhere to OCR-D conventions is another story, but there I cannot offer a solution for now.

That aspect should be solved in the current core, too.

> [0f09f4a](https://github.com/qurator-spk/sbb_textline_detection/commit/0f09f4a1f6b5d61987a0e6f14c9a5a4623fa3b26) says it's resolved.

Looks fine!
