### ISSUE TITLE
improve ocrd-tool.json

### ISSUE THREAD

**Issue by bertsky** [qurator-spk/sbb_textline_detection#31]
The description and classification of the `ocrd-tool.json` could better reflect what is really going on:

* `description = 'Detect lines'` – please state here what the README already says
* `steps = 'layout/segmentation/line' ` – should also have `layout/segmentation/region` (or just `layout/segmentation`), maybe even `preprocessing/optimization/deskewing` (IIUC)
* `categories = "Image preprocessing", "Layout analysis", "Text recognition and optimization"` – should only be `Layout analysis`

**Comment by mikegerber** [comment]
Thanks!
