### ISSUE TITLE
TextLine coordinates too coarse

### ISSUE THREAD

**Issue by bertsky** [qurator-spk/sbb_textline_detection#33]
Would it be possible to get good polygonal outlines from the text line segmentation instead of coarse bounding boxes?

There is a stark contrast between the precise contours of the text regions (which never overlap) and the coarse rectangles of text lines inside them (which often extrude beyond their parent and overlap between adjacent lines).

This makes it risky to apply line-level dewarping afterwards, and requires an OCR engine that can cope with intruders in the line image. In the example given in #29, I get these line images from `ocrd-cis-ocropy-dewarp`:

![OCR-D-IMG-DEW-SBB_0001_r21_l24](https://user-images.githubusercontent.com/38561704/83109663-0c60ee00-a0c2-11ea-82b1-acd8d6a29a14.png)

![OCR-D-IMG-DEW-SBB_0001_r21_l25](https://user-images.githubusercontent.com/38561704/83109644-05d27680-a0c2-11ea-8923-2ed38a39f8ee.png)

![OCR-D-IMG-DEW-SBB_0001_r21_l26](https://user-images.githubusercontent.com/38561704/83109637-01a65900-a0c2-11ea-9303-ec1087509486.png)

![OCR-D-IMG-DEW-SBB_0001_r21_l27](https://user-images.githubusercontent.com/38561704/83109624-fce1a500-a0c1-11ea-88db-cb770fbb1ddd.png)

![OCR-D-IMG-DEW-SBB_0001_r21_l28](https://user-images.githubusercontent.com/38561704/83109608-f7845a80-a0c1-11ea-9586-5ec657d67764.png)

![OCR-D-IMG-DEW-SBB_0001_r21_l29](https://user-images.githubusercontent.com/38561704/83109590-f05d4c80-a0c1-11ea-8186-dccafe477e1e.png)

![OCR-D-IMG-DEW-SBB_0001_r21_l30](https://user-images.githubusercontent.com/38561704/83109577-eb989880-a0c1-11ea-81d2-208451418540.png)

![OCR-D-IMG-DEW-SBB_0001_r21_l31](https://user-images.githubusercontent.com/38561704/83109567-e6d3e480-a0c1-11ea-810f-6ac7e34c80b6.png)

![OCR-D-IMG-DEW-SBB_0001_r21_l32](https://user-images.githubusercontent.com/38561704/83109515-d3287e00-a0c1-11ea-9a53-b124f955908e.png)

![OCR-D-IMG-DEW-SBB_0001_r21_l33](https://user-images.githubusercontent.com/38561704/83109546-e0456d00-a0c1-11ea-84ac-a287ae97e44d.png)

![OCR-D-IMG-DEW-SBB_0001_r21_l34](https://user-images.githubusercontent.com/38561704/83109478-c6a42580-a0c1-11ea-895d-c9da9d42642d.png)

**Comment by vahidrezanezhad** [comment]
@bertsky We can set more tight textlines but this  also has its own disadvantages. By the way we will publish a new tool which throws contours for textlines not rectangles. however mentioned method costs us more processing time!

**Comment by bertsky** [comment]
@vahidrezanezhad 
> We can set more tight textlines but this also has its own disadvantages. however mentioned method costs us more processing time!

Then why not make that behaviour optional (with an ocrd-tool.json parameter), so the user can decide what is needed (precision or performance) for her workflow?

> By the way we will publish a new tool which throws contours for textlines not rectangles.

Where?

And why did you close the issue already?

**Comment by vahidrezanezhad** [comment]
Dear @bertsky ,
First of all you can see the tool which gives texlines as contour here
" https://github.com/vahidrezanezhad/newspapers_regions_and_reading_order_curved_lines "
But the reason it is not integrated as an option to the current model is that, the new tool will be another tool which can give also the reading order of textregions. The other reason is it is still under development. If you use this tool (of course I can share the models with you :) ) you will see that I am writing textlines contours on the deskewed image and not original image, but based on our internal decisions in sbb we decided to write results on org image again.

**Comment by bertsky** [comment]
@vahidrezanezhad understood – I'll try to follow. Thanks for clarifying!
