### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [qurator-spk/sbb_textline_detection#39]
.

**Comment by vahidrezanezhad** [comment]
Dear @deepseek,

I have used heuristic method to find the order of regions. Key point is to know that we can already detect separators by layout detection and on the other hand this separators include information about text ordering :)

**Comment by vahidrezanezhad** [comment]
Dear @deepseek,

I have used heuristic method to find the order of regions. Key point is to know that we can already detect separators by layout detection and on the other hand this separators include information about text ordering :)

**Comment by vahidrezanezhad** [comment]
Dear @deepseek,

I have used heuristic method to find the order of regions. Key point is to know that we can already detect separators by layout detection and on the other hand this separators include information about text ordering :)

**Comment by vahidrezanezhad** [comment]
Dear @deepseek,

I have used heuristic method to find the order of regions. Key point is to know that we can already detect separators by layout detection and on the other hand this separators include information about text ordering :)

**Comment by vahidrezanezhad** [comment]
Dear @deepseek,

I have used heuristic method to find the order of regions. Key point is to know that we can already detect separators by layout detection and on the other hand this separators include information about text ordering :)

**Comment by vahidrezanezhad** [comment]
Dear @deepseek,

I have used heuristic method to find the order of regions. Key point is to know that we can already detect separators by layout detection and on the other hand this separators include information about text ordering :)

**Comment by deepseek** [comment]
excellent
