### ISSUE TITLE
difference between this and eynollah?

### ISSUE THREAD

**Issue by SB2020-eye** [qurator-spk/sbb_textline_detection#56]
Hi. I'd appreciate knowing what the differences are between sbb_textline_detection and eynollah. Thanks in advance.

**Comment by cneud** [comment]
Hi, basically `eynollah` will be a replacement for `sbb_textline_detection` with a superset of features integrating [more functionality](https://github.com/qurator-spk/eynollah#how-to-use) like scaling and additional heuristics that help to improve both, layout analysis and textline detection. 

We are currently working on an overhaul of the codebase for `eynollah` that should make it easier for others to use/contribute and also adding an OCR-D CLI . Once that's done, we will phase out `sbb_textline_detection` (in fact active development already concentrates on `eynollah`) and deprecate this one.

**Comment by SB2020-eye** [comment]
Thank you! I wondered if that might be the case.
